### ISSUE TITLE
SSL error

### ISSUE THREAD

**Issue by antichown** [renatoathaydes/rawhttp#40]
ssl does not send data

java.net.SocketException: Connection reset

at rawhttp.core.HttpMetadataParser.parseStartLine(HttpMetadataParser.java:285)
	at rawhttp.core.HttpMetadataParser.parseStatusLine(HttpMetadataParser.java:192)
	at rawhttp.core.RawHttp.parseResponse(RawHttp.java:209)
	at rawhttp.core.RawHttp.parseResponse(RawHttp.java:192)

**Comment by renatoathaydes** [comment]
It works if you use a `SSLSocket`. Please show your code if you want help with this.

**Comment by antichown** [comment]
yeah, it worked, thank you.
