### ISSUE TITLE
ReqInEdit: Replace Nashorn with GraalVM.js

### ISSUE THREAD

**Issue by renatoathaydes** [renatoathaydes/rawhttp#49]
Nashorn is deprecated in Java 11 and will be removed in Java 17. Running on Java 11 already causes warnings.

**Comment by mpgirro** [comment]
Hi there. Thank you for replacing Nashorn, so it won't be a blocker for upgrading to Java 17! 

Is there a timeline when we may expect this improvement to be shipped?

**Comment by renatoathaydes** [comment]
It's already done, but I am having some trouble making tests run in CI.

https://github.com/renatoathaydes/rawhttp/actions

I am actually writing a blog post to investigate in detail the differences between Nashorn and graal.js to see if I can figure out why the builds are a mess in CI now. Testing things locally, it all seems to work fine!

**Comment by renatoathaydes** [comment]
FYI Nashorn can still be used on Java 17: https://github.com/openjdk/nashorn

I've tested that and it works perfectly, as with Java 11, on Java 17.

Performance is even quite a lot better!

**Comment by mpgirro** [comment]
Good to know. Thank you for the info!

**Comment by renatoathaydes** [comment]
The code in question is this:

```java
import import jdk.nashorn.api.scripting.NashornScriptEngine;

...

(NashornScriptEngine) new ScriptEngineManager().getEngineByName("nashorn");
```

@grexe Are you using the https://github.com/openjdk/nashorn I posted above with JDK 17?

The way I did the cast was safe as Nashorn was part of the OpenJDK API until now! But yeah, since they removed that I'll have to release a new version that works only on JDK 17+, I think... I 'll have a look into this as the changes to use GraalVM.js didn't go as well as I'd hoped (and I think I will continue using the new Nashorn "library", at least until IntelliJ moves to GraalVM.js, if they ever do ... as far as I know, they haven't done that or plan to do it?)

**Comment by grexe** [comment]
yes I'm using OpenJDK Nashorn `org.openjdk.nashorn, nashorn-core, 15.3` and the `org.openjdk.nashorn.api.scripting.NashornScriptEngineFactory` with OpenJDK `17.0.1`.

I wouldn't hold my breath for GraalVM just yet, it's too early and also not supported by the common frameworks yet - Spring Boot e.g. is just working on it.

**Comment by renatoathaydes** [comment]
Building a multi-release jar was not hard, but it seems the Nashorn library doesn't work at all in Java 17.

I tested before but it was a basic check only... now that I try to run a http file, it fails with an error that seems to indicate Nashorn still has code in the JVM linking to the wrong classes.

```
▶ java -cp build/libs/rawhttp.jar rawhttp.cli.Main run ../rawhttp-cli-tests/src/test/resources/reqin-edit-tests/tests/tests.http
RUNNING ON JAVA 17
HTTP/1.1 200 OK
Content-Type: text/plain
Content-Length: 9

something
Exception in thread "main" java.lang.NoClassDefFoundError: jdk/nashorn/api/scripting/ScriptObjectMirror
        at java.base/java.lang.Class.getDeclaredMethods0(Native Method)
        at java.base/java.lang.Class.privateGetDeclaredMethods(Class.java:3402)
        at java.base/java.lang.Class.privateGetPublicMethods(Class.java:3427)
        at java.base/java.lang.Class.getMethods(Class.java:2019)
        at jdk.dynalink/jdk.dynalink.beans.AccessibleMembersLookup.lookupAccessibleMembers(AccessibleMembersLookup.java:178)
        at jdk.dynalink/jdk.dynalink.beans.AccessibleMembersLookup.<init>(AccessibleMembersLookup.java:93)
        at jdk.dynalink/jdk.dynalink.beans.FacetIntrospector.<init>(FacetIntrospector.java:89)
        at jdk.dynalink/jdk.dynalink.beans.StaticClassIntrospector.<init>(StaticClassIntrospector.java:74)
        at jdk.dynalink/jdk.dynalink.beans.StaticClassLinker$SingleClassStaticsLinker.createFacetIntrospector(StaticClassLinker.java:122)
        at jdk.dynalink/jdk.dynalink.beans.AbstractJavaLinker.<init>(AbstractJavaLinker.java:116)
        at jdk.dynalink/jdk.dynalink.beans.AbstractJavaLinker.<init>(AbstractJavaLinker.java:108)
        at jdk.dynalink/jdk.dynalink.beans.StaticClassLinker$SingleClassStaticsLinker.<init>(StaticClassLinker.java:95)
        at jdk.dynalink/jdk.dynalink.beans.StaticClassLinker$1.computeValue(StaticClassLinker.java:87)
        at jdk.dynalink/jdk.dynalink.beans.StaticClassLinker$1.computeValue(StaticClassLinker.java:84)
        at java.base/java.lang.ClassValue.getFromHashMap(ClassValue.java:228)
        at java.base/java.lang.ClassValue.getFromBackup(ClassValue.java:210)
        at java.base/java.lang.ClassValue.get(ClassValue.java:116)
        at jdk.dynalink/jdk.dynalink.beans.StaticClassLinker.getGuardedInvocation(StaticClassLinker.java:184)
        at jdk.dynalink/jdk.dynalink.beans.BeansLinker$NoSuchMemberHandlerBindingLinker.getGuardedInvocation(BeansLinker.java:207)
        at org.openjdk.nashorn.internal.runtime.linker.NashornBeansLinker.getGuardedInvocation(NashornBeansLinker.java:169)
        at org.openjdk.nashorn.internal.runtime.linker.NashornStaticClassLinker.delegate(NashornStaticClassLinker.java:111)
        at org.openjdk.nashorn.internal.runtime.linker.NashornStaticClassLinker.getGuardedInvocation(NashornStaticClassLinker.java:104)
        at jdk.dynalink/jdk.dynalink.linker.support.CompositeTypeBasedGuardingDynamicLinker.getGuardedInvocation(CompositeTypeBasedGuardingDynamicLinker.java:161)
        at jdk.dynalink/jdk.dynalink.linker.support.CompositeGuardingDynamicLinker.getGuardedInvocation(CompositeGuardingDynamicLinker.java:109)
        at jdk.dynalink/jdk.dynalink.LinkerServicesImpl.lambda$getGuardedInvocation$0(LinkerServicesImpl.java:137)
        at jdk.dynalink/jdk.dynalink.LinkerServicesImpl.getWithLookupInternal(LinkerServicesImpl.java:168)
        at jdk.dynalink/jdk.dynalink.LinkerServicesImpl.getGuardedInvocation(LinkerServicesImpl.java:135)
        at jdk.dynalink/jdk.dynalink.DynamicLinker.relink(DynamicLinker.java:241)
        at org.openjdk.nashorn.internal.scripts.Script$Recompilation$31$26719A$\^eval\_.__runAllTests__(<eval>:845)
        at org.openjdk.nashorn.internal.runtime.ScriptFunctionData.invoke(ScriptFunctionData.java:648)
        at org.openjdk.nashorn.internal.runtime.ScriptFunction.invoke(ScriptFunction.java:513)
        at org.openjdk.nashorn.internal.runtime.ScriptRuntime.apply(ScriptRuntime.java:520)
        at org.openjdk.nashorn.api.scripting.ScriptObjectMirror.callMember(ScriptObjectMirror.java:187)
        at org.openjdk.nashorn.api.scripting.NashornScriptEngine.invokeImpl(NashornScriptEngine.java:379)
        at org.openjdk.nashorn.api.scripting.NashornScriptEngine.invokeFunction(NashornScriptEngine.java:186)
        at com.athaydes.rawhttp.reqinedit.js.ScriptEngineWrapper.invokeFunction(ScriptEngineWrapper.java:27)
        at com.athaydes.rawhttp.reqinedit.js.JsEnvironment.invoke(JsEnvironment.java:124)
        at com.athaydes.rawhttp.reqinedit.js.JsEnvironment.runAllTests(JsEnvironment.java:119)
        at com.athaydes.rawhttp.reqinedit.js.JsEnvironment.runResponseHandler(JsEnvironment.java:109)
        at com.athaydes.rawhttp.reqinedit.ReqInEditUnit.runResponseScript(ReqInEditUnit.java:161)
        at com.athaydes.rawhttp.reqinedit.ReqInEditUnit.lambda$run$1(ReqInEditUnit.java:123)
        at java.base/java.util.Optional.map(Optional.java:260)
        at com.athaydes.rawhttp.reqinedit.ReqInEditUnit.run(ReqInEditUnit.java:123)
        at com.athaydes.rawhttp.reqinedit.ReqInEditUnit.run(ReqInEditUnit.java:99)
        at rawhttp.cli.Main.runHttpFile(Main.java:259)
        at rawhttp.cli.Options.run(OptionsParser.java:188)
        at rawhttp.cli.Main.main(Main.java:56)
Caused by: java.lang.ClassNotFoundException: jdk.nashorn.api.scripting.ScriptObjectMirror
        at java.base/jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:641)
        at java.base/jdk.internal.loader.ClassLoaders$AppClassLoader.loadClass(ClassLoaders.java:188)
        at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:520)
        ... 47 more
```

I am not sure whom to complain now :) it's late now so I will continue thinking about this tomorrow or later this week. If anyone can help, I appreciate.

**Comment by renatoathaydes** [comment]
Tested with Zulu and OpenJDK 17.0.2.

**Comment by renatoathaydes** [comment]
False alarm!!! I got it working, there was a Java class that was being called by my JS script which still used the old Nashorn types!

[Tiny fix](https://github.com/renatoathaydes/rawhttp/commit/5b51520e72e68001fe320a14b370e3ec894b40a9) and it works:

```
▶ java -version
openjdk version "17.0.2" 2022-01-18
OpenJDK Runtime Environment (build 17.0.2+8-86)
OpenJDK 64-Bit Server VM (build 17.0.2+8-86, mixed mode, sharing)

projects/rawhttp/rawhttp-cli  multi-jar-java17 ✔                                                                                                                                 1m  
▶ java -cp build/libs/rawhttp.jar rawhttp.cli.Main run ../rawhttp-cli-tests/src/test/resources/reqin-edit-tests/tests/tests.http
HTTP/1.1 200 OK
Content-Type: text/plain
Content-Length: 9

something
TEST OK (14ms): response is 200
HTTP/1.1 200 OK
Content-Type: text/plain
Content-Length: 18

Received:something
TEST OK (3ms): response again is 200
TEST OK (4ms): body is as expected
```

I will do more testing tomorrow to make sure it's all working on Java 8 as well (though GitHubActions should show whether it's working) then release this!

**Comment by renatoathaydes** [comment]
100% GREEN! https://github.com/renatoathaydes/rawhttp/actions/runs/1757883520

The req-in-edit jar is now a multi-release jar, so it works on Java 8 all the way to Java 17+... for any version since Nashorn was removed, which I think was Java 15, the nashorn library must be included in the classpath.

I will release the CLI jar in two versions, one compiled with Java 8 and NOT including Nashorn (`rawhttp.jar`) and another one that includes also Nashorn and its dependencies (`rawhttp-jdk17.jar`).

Should be up on Maven Central soon.

**Comment by renatoathaydes** [comment]
It's up: https://search.maven.org/artifact/com.athaydes.rawhttp/rawhttp-cli/1.4.0/jar
and https://search.maven.org/artifact/com.athaydes.rawhttp/rawhttp-req-in-edit/0.3.0/jar

**Comment by mpgirro** [comment]
Thank you very much for fixing this :)

**Comment by renatoathaydes** [comment]
I decided to not use GraalVM.js for the moment being.

As far as I know, JetBrains is using Nashorn, so I will keep using that, specially now that RawHTTP-CLI works even on Java 17+, and unless JetBrains changes their dependency on Nashorn, this will be the case for the foreseeable future.
